# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewReleaseNoteFlat',
        ),
    ]
