# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_reviewreleasenoteflat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReleaseNoteFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_app_id', models.IntegerField()),
                ('is_review', models.BooleanField(default=True)),
                ('review_id', models.IntegerField(default=0)),
                ('body', models.TextField(blank=True, null=True)),
                ('star_rating', models.IntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('user_apple_id', models.IntegerField(default=0)),
                ('user_reviews_url', models.URLField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('crawled_on', models.DateTimeField()),
            ],
        ),
    ]
